version: "3"
# volumes:
#   gatsby-node-modules:
#   gatsby-cache:
#   gatsby-public:
services:
  website:
    container_name: gatsby-website
    image: gatsby-website
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: yarn start:dev
    ports:
      - "3000:3000" # react
      - "8000:8000" # gatsby develop
      - "9000:9000" # gatsby serve
  volumes:
    - .:/workspace:cached
    # - gatsby-node-modules:/workspace/node_modules
    - /workspace/node_modules
    # - gatsby-cache:/workspace/.cache
    - /workspace/.cache
    # - gatsby-public:/workspace/public
    - /workspace/public
  environment:
    - WATCHPACK_POLLING=true # react and gatsby hot reloading
